### ISSUE TITLE
I get an error when trying to run this on a Raspberry Pi 3

### ISSUE THREAD

**Issue by pipja** [Joentje/nordvpn-proxy#26]
this is the output:

`standard_init_linux.go:211: exec user process caused "exec format error"`

Any idea what's happening?

**Comment by Joentje** [comment]
There is no support yet for ARM. The issue is the same as #17

**Comment by pipja** [comment]
@Joentje I actually managed to do it by compiling the image on the pi itself. Works like a charm now. Cheers.

**Comment by Joentje** [comment]
@pipja cool! :)

**Comment by Joentje** [comment]
@pipja You can now try the latest tag. I'm trying to fix it in #34
