### ISSUE TITLE
Is privoxy in effect

### ISSUE THREAD

**Issue by ndwalters** [Joentje/nordvpn-proxy#27]
Is privoxy in effect (by filtering web traffic) or just functioning as a proxy only?

I cant seem to get Deluge to access certain sites via the docker image.

**Comment by Joentje** [comment]
@ndwalters as far as I know only for proxy only. So you can use a plugin in for example chrome to route traffic using privoxy that will use the vpn.

If you want to route traffic from Deluge through the vpn, you can use the option to use other Docker container network. Only if Deluge is running in a container.
