### ISSUE TITLE
Question: remotely access my server via VPN, access services running via nordvpn-proxy

### ISSUE THREAD

**Issue by zilexa** [Joentje/nordvpn-proxy#28]
Background: Ubuntu Budgie 20.04.1 on an Intel based server/workstation, using Docker and Compose to build my homeserver.

Just wondering if this would be possible:
Currently I have a few Docker services running smoothly via the NordVPN-proxy docker. I can access their webUIs as long as I am within my LAN (192.168.88.0/24). All works fine.

Now I install PiVPN on the server, and set up Wireguard VPN server. I created client.conf files, in allowing only 192.168.88.0/24 addresses via the VPN. This works: I can remotely access docker services running on the server/host machine like Portainer now, while normal internet traffic on the client bypasses the tunnel. Basically, the VPN connection is only used to access my LAN. All fine.

However I cannot access the webUIs of docker services that are running behind NordVPN-proxy. Those ports seem inaccessible. They are only accessible via LAN. Is there a way to change this, without safety risks?

**Comment by Joentje** [comment]
@zilexa I think it has to due to network isolation of the Docker network. Maybe you can expose the Docker services via multiple Docker networks. Or expose the UI's via a reverse proxy like Nginx.
