### ISSUE TITLE
Why LOCAL_NETWORK is useful?

### ISSUE THREAD

**Issue by MurattuW** [Joentje/nordvpn-proxy#31]
Hello,

I have commented the line:
https://github.com/Joentje/nordvpn-proxy/blob/563d80f591c7532eeaa4bab2dc2eb9d7495e6fe2/app/privoxy/run#L7

And it works just fine. Why this line is needed?

Best regards,

**Comment by MurattuW** [comment]
Okay, never mind... Without LOCAL_NETWORK it only works on the main host, not on other computers over the same network. But I still don't exactly understand why this is needed. Is there any alternatives?

**Comment by Joentje** [comment]
That's indeed the case, you will need to specify your local network. I'm not aware of an other solution.
