### ISSUE TITLE
P2P Servers

### ISSUE THREAD

**Issue by steveoleary** [Joentje/nordvpn-proxy#48]
Hi,

love this image, thanks for putting it together. Would it be possible to allow an environment option to filter by server category, e.g, P2P. I understand that this isn't really relevant for the proxy per se but for people using the container as the network service to something else like a torrent client it could be a useful add?

**Comment by Joentje** [comment]
Hi @steveoleary, thank you for your complement :). There is a Pull Request open for this, but it still needs some work. Check out #41

**Comment by steveoleary** [comment]
Ah great, i'll take a look at that issue then, feel free to close this one in that case :-) Thanks

**Comment by steveoleary** [comment]
Sorry, I'm such a newb haha, realised I could do it myself 🤦‍♂️
