### ISSUE TITLE
Better handle openvpn startup errors

### ISSUE THREAD

**Issue by SijmenHuizenga** [Joentje/nordvpn-proxy#49]
Hi there, Thanks a lot for this project, t has helped me out a lot. I really appreciate it!

* When an error occurs during the execution of `ovpn/run`, or one of the scripts it sources, `runsvdir` restarts the script immediately.
* The `api.nordvpn.com` endpoints are rate-limited through cloudflare.

So, if (for whatever reason) OpenVPN fails to start, the `ovpn.zip`, `api.nordvpn.com/server` and `api.nordvpn.com/v1/servers/recommendations` are re-downloaded again. If this happens a few times, the `api.nordvpn` will be rate-limited (like we see in #42) and the `ovpn/run` script will rail even faster (during the `curl` calls). This results in even more requests to the `api.nordvpn` endpoint, ending up in an even longer rate-limit. 

This behaviour has happened to me. In 6 days it downloaded around 3TB.

We could kill the docker container when an error occurs in `ovpn/run`. To me, launching openvpn conceptually is part of the bootstrapping of the container. If openvpn fails the, whole container fails, seems reasonable.

Another solution would be to implement some back-off, like sleeping more and more time between retries.

**Comment by Joentje** [comment]
This is indeed an issue. When there is for some reason, like a filter issue in #50. It will retry over and over again. This is not ideal. Especially when you don't see the error, you probably are already hitting a rate limit.

Seems fair to me to say when Openvpn cannot connect, the container should fail.
