### ISSUE TITLE
Filter recommended servers to only include vpn-capable servers 

### ISSUE THREAD

**Issue by SijmenHuizenga** [Joentje/nordvpn-proxy#50]
Apparently, not all vpn servers support openvpn. Servers that do not support vpn are not included in the `ovpn.zip` folder. 

At the moment, if you are unlucky and openvpn recommends a server that does not support openvpn, the problem described in #49 will happen because openvpn can't find the server file.

From what I can find, the `https://api.nordvpn.com/v1/servers/recommendations` does not support filtering recommended servers based on technology support. 

I think the solution should be to use the `https://nordvpn.com/wp-admin/admin-ajax.php` endpoind as described [here](https://blog.sleeplessbeastie.eu/2019/01/14/how-to-use-terminal-to-display-servers-recommended-by-nordvpn/). That endpoint _does_ support tech-filtering. It is also the same endpoint used by `https://nordvpn.com/servers/tools/` when you select 'show advanced options.

**Comment by gerwim** [comment]
Ah, this is the same exact issue I actually had. My openvpn would not start because of it being unable to parse the configuration file.

The API does support filtering though, e.g.: `https://api.nordvpn.com/v1/servers/recommendations?filters[servers_technologies][identifier]=openvpn_udp&limit=1`.

I'll create a PR later this week.

**Comment by gerwim** [comment]
@SijmenHuizenga I've made the (small) PR, and I just noticed you submitted a PR too. Ah well :-)

**Comment by Joentje** [comment]
@SijmenHuizenga thank you for reporting. This is indeed crucial to make it work if somehow a server does not support a certain protocol. Just merged @gerwim PR that will solve this.
