### ISSUE TITLE
Custom DNS IP's aren't used in OpenVPN

### ISSUE THREAD

**Issue by matt-laird** [Joentje/nordvpn-proxy#62]
For example, used Cloudflare resolvers:
![Screenshot 2021-04-23 232417](https://user-images.githubusercontent.com/14907718/115931228-12567f00-a48b-11eb-8332-1a37005cb595.jpg)
OpenVPN gets the default NordVPN DNS resolvers:
![Screenshot 2021-04-23 232301](https://user-images.githubusercontent.com/14907718/115931233-1387ac00-a48b-11eb-9672-ead30503b161.jpg)

**Comment by Joentje** [comment]
Thanks for reporting. Somehow this look indeed enforced to the Nordvpn DNS. Need to find some time to take a look :)

**Comment by matt-laird** [comment]
Did some digging, seems you need to add some logic that appends the DNS options in the start command for OpenVPN.
Arguments to add would be something like this:
`openvpn --push "dhcp-option DNS 1.1.1.1"`
reference:
* https://openvpn.net/community-resources/how-to/#dhcp

**Comment by matt-laird** [comment]
Closing this off as I better understand the OpenVPN server and client lifecycle now. This is not an issue, the OpenVPN client gets those settings pushed to it from the server and is forced to abide by those settings.
